docs ja: translate coc v1.3 into Japanese
cncf/foundation pull request #631
Opened 2023-09-01 19:45 UTC by Okabe-Junya

## WHAT I CHANGED

The Japanese version of the Code of Conduct, which had not been updated since Code of Conduct v1.1, has now been updated to v1.3.

Since two minor versions have been updated, the range of changes is somewhat extensive.

2024-01-27 08:28 UTC, Okabe-Junya commented
@amye @nate-double-u 

Hi folks!!

I want to merge this PR. Since I couldn't find a reviewer for the Japanese localization within this project, may I ask a reviewer from another cncf project who is involved in Japanese localization? (maybe cncf/glossary)

2024-01-31 01:55 UTC, nate-double-u commented
Hi @Okabe-Junya, it doesn't hurt to ask. I think you could reach out on the [CNCF #glossary-localizations](https://cloud-native.slack.com/archives/C02N2RGFXDF) slack channel.

2024-01-31 01:56 UTC, nate-double-u commented
(I just looked, and there is a [#glossary-localizations-japanese](https://cloud-native.slack.com/archives/C057F81GFUG) channel too.

2024-01-31 06:05 UTC, Okabe-Junya commented
Thanks @nate-double-u !!

I asked for Japanese reviewers on [Slack](https://cloud-native.slack.com/archives/C057F81GFUG/p1706679922453449)

Once the review process is complete, please merge (approve) :)

2024-01-31 15:45 UTC, Okabe-Junya commented
@kaitoii11

I Would appreciate if you could do a technical review in Japanese :)

2024-02-01 02:41 UTC, Okabe-Junya commented
PTAL @naonishijima

This is friendly ping :)

2024-02-01 05:50 UTC, naonishijima commented on code-of-conduct-languages/jp.md
>  私たちは、経験レベル、性別、性の自認および表明、性的嗜好、障がい、個人的な外見、身体の大きさ、人種、民族、年齢、宗教、または国籍に関係なく、このプロジェクトへの参加を、全員にとってハラスメントがない経験にすることを約束します。
v1.1からv1.3のあいだにいくつか追加されています。
「年齢、身体の大きさ、カースト、障害、民族性、経験レベル、家族構成、性別、性自認と性表現、配偶者の有無、軍人または退役軍人の地位、国籍、容姿、人種、宗教、性的指向、社会経済的地位、部族、その他あらゆる多様性の側面に関係なく。」

2024-02-01 05:50 UTC, naonishijima commented on code-of-conduct-languages/jp.md
> +CNCFコミュニティのコントリビュータ、メンテナ、およびその参加者は、オープンかつ快適なコミュニティを促進するために、問題の報告、機能要求の投稿、ドキュメントの更新、プルリクエストまたはパッチ、および他の活動を通して貢献するすべての人々を尊重することを誓います。
「〜の投稿、カンファレンスやイベントへの参加、ドキュメント〜」のカンファレンス〜が抜けています。

2024-02-01 05:50 UTC, naonishijima commented on code-of-conduct-languages/jp.md
> +* 望ましくない身体的な接触
「望ましくない身体的な接触」の次の行が抜けています。
「歓迎されない性的または恋愛的な注目や誘い」

2024-02-01 11:14 UTC, kaitoii11 requested changes

2024-02-01 11:14 UTC, kaitoii11 commented on code-of-conduct-languages/jp.md
> +* インシデントを報告したり、証人としてインシデントに関する情報を提供したりするための報復行為。
```suggestion
* インシデントを報告したり、証人としてインシデントに関する情報を提供したりした人へ対する報復行為。
```

2024-02-01 11:14 UTC, kaitoii11 commented on code-of-conduct-languages/jp.md
> +プロジェクトのメンテナは、この行動規範に準拠していないコメント、コミット、コード、Wikiの編集、問題、他のコントリビューションを削除、編集、または却下する権利および責任を持っています。プロジェクトのメンテナは、この行動規範を採用することで、公正かつ一貫した方法で、これらの原則を本プロジェクトの管理におけるすべての要素に適用することに注力します。本行動規範を遵守または施行しないプロジェクトのメン
「本プロジェクト」は何を指すのか分からないので、「プロジェクト」で良いかと思います。

2024-02-01 11:14 UTC, kaitoii11 commented on code-of-conduct-languages/jp.md
> +CNCFの憲章と一貫して、この行動規範に対する実質的な変更は、技術監督委員会の承認が必要です。
Technical Oversight Committeeは組織名なのでそのままでよいかと思います。

2024-02-01 11:14 UTC, kaitoii11 commented on code-of-conduct-languages/jp.md
謝辞の追加もお願いします。

2024-02-01 13:53 UTC, Okabe-Junya commented on code-of-conduct-languages/jp.md
>  私たちは、経験レベル、性別、性の自認および表明、性的嗜好、障がい、個人的な外見、身体の大きさ、人種、民族、年齢、宗教、または国籍に関係なく、このプロジェクトへの参加を、全員にとってハラスメントがない経験にすることを約束します。
ありがとうございます。

https://github.com/cncf/foundation/pull/631/commits/5064bee0e6f23cd3cb5c06996e9975e6929b3e82 で修正しました

2024-02-01 13:56 UTC, Okabe-Junya commented on code-of-conduct-languages/jp.md
> +* その他、専門的な場において不適切とみなされうる行為
https://github.com/cncf/foundation/pull/631/commits/a11346c6738a38bda202bd732e9ee9a4611b4783 で修正しました

2024-02-02 00:55 UTC, Okabe-Junya commented on code-of-conduct-languages/jp.md
> +CNCFの憲章と一貫して、この行動規範に対する実質的な変更は、技術監督委員会の承認が必要です。
https://github.com/cncf/foundation/pull/631/commits/905f76a65665f25b97cc93661152e774adf8b376 で修正しました

2024-02-02 01:18 UTC, Okabe-Junya commented on code-of-conduct-languages/jp.md
> +CNCFコミュニティは開かれており、包括的であり、敬意をもって接されます。コミュニティのすべてのメンバーは、自分自身のアイデンティティが尊重される権利を持っています。
ありがとうございます。

https://github.com/cncf/foundation/pull/631/commits/012dcf33c88d4d0829f7d486317b0608b9605ec9 で修正しました

2024-02-02 01:19 UTC, Okabe-Junya commented on code-of-conduct-languages/jp.md
>  * 個人ではなく、コミュニティ全体として何が最善策かを重視する
ありがとぐおざいます、了解しました。

https://github.com/cncf/foundation/pull/631/commits/6fb263059d341ee8ab5a96ef17a774f8e2852586 で修正しました

2024-02-02 02:23 UTC, Okabe-Junya commented on code-of-conduct-languages/jp.md
> +CNCFコミュニティのコントリビュータ、メンテナ、およびその参加者は、オープンかつ快適なコミュニティを促進するために、問題の報告、機能要求の投稿、ドキュメントの更新、プルリクエストまたはパッチ、および他の活動を通して貢献するすべての人々を尊重することを誓います。
ありがとうございます。

https://github.com/cncf/foundation/pull/631/commits/9b5cf683316d6f2a1cab51a73c08031331c78953 で修正しました

2024-02-02 02:24 UTC, Okabe-Junya commented on code-of-conduct-languages/jp.md
> +プロジェクトのメンテナは、この行動規範に準拠していないコメント、コミット、コード、Wikiの編集、問題、他のコントリビューションを削除、編集、または却下する権利および責任を持っています。プロジェクトのメンテナは、この行動規範を採用することで、公正かつ一貫した方法で、これらの原則を本プロジェクトの管理におけるすべての要素に適用することに注力します。本行動規範を遵守または施行しないプロジェクトのメン
ありがとうございます、

https://github.com/cncf/foundation/pull/631/commits/2f9f6cbdd7eced8c519cdf38ca3f65eb053b51c7 で修正しました

2024-02-02 02:28 UTC, Okabe-Junya commented
Thank you for the thorough review. I have fixed.

I appreciate if you could check it again.

2024-02-02 02:29 UTC, Okabe-Junya commented
Since this PR has many commits, use `squash and merge`

2024-02-02 04:28 UTC, naonishijima approved these changes
LGTM

2024-02-02 11:45 UTC, kaitoii11 approved these changes
LGTM

2024-02-02 12:57 UTC, Okabe-Junya commented
Thank you!!

PATL @nate-double-u

please merge :)

2024-02-03 01:07 UTC, nate-double-u approved these changes
Thanks for this @Okabe-Junya, I appreciate you coordinating these changes.

Thanks for the reviews @kaitoii11 and @naonishijima!

/lgtm

2024-02-03 01:09 UTC, merged